### ISSUE TITLE
Is it possible to use Traces with Async / Await instead of fibers?

### ISSUE THREAD

**Issue by jamesgibson14** [monti-apm/monti-apm-agent#52]
Once an await call is made in Meteor it looses scope to the current fiber, I was trying to do 2 custom Traces on a method but the second one wouldn't work because ( I assume ) it couldn't start with out a fiber.
Here is some code example from inside a Meteor.method:
```js:
async run({ xid, docNum, domain }){
    ....

    const event = Monti.startEvent('xStoredProc', {
      procParams
    })
    // first await:
    const [err, res] = await model.asyncStoredProc('B1FAM_FA_WO_STAGE_COMPLETE_NOMSG', procParams)
    // this custom event works and shows up in MontiAPM
    Monti.endEvent(event, {
      additionalDetails: true
    });
    
     // second await, at this point there in no scoped Meteor.fiber so event2 never shows up in MontiAPM
    const event2 = Monti.startEvent('xSync', {
      typeName,
      xid,
    });
    const synced = await Argus.ExternalDataController.sync({ typeName, xidList: [{ xid }], user, domain, })
    Monti.endEvent(event2, {
      additionalDetails: true
    });
    return res;
  }
```

**Comment by jamesgibson14** [comment]
I am sure you are aware of the discussions for Meteor to move away from Fibers.
https://github.com/meteor/meteor/pull/12028
In my app I have already transitioned most of my  methods to async/await, which is great, but I still run into these Fibers issues every now and then.

**Comment by zodern** [comment]
Meteor actually implements promises and async/await using Fibers on the server in order to preserve the context. Your code looks like it should work correctly. Could you please create a reproduction? Also, it might be worth checking if `Meteor.userId()` works correctly throughout the method. If it doesn't, this might be a bug in Meteor.

Eventually we will support using async hooks instead of fibers, but that will have to wait until Meteor allows disabling fibers since fibers and async hooks aren't completely compatible.
