### ISSUE TITLE
Problem of wrong context when using monti

### ISSUE THREAD

**Issue by DavidSichau** [monti-apm/monti-apm-agent#79]
As soon as we install monti-apm-agent we have problems in our test cases:

Is it somehow possible to disable the attachment of monti to the EventLoop via environment variables?

```
 Error: done() called multiple times in hook <useMethod "before all" hook: wrappedFunction in "useMethod">; in addition, done() received error: TypeError: 'now' called on an object that is not a valid instance of Performance.
     at now (/home/sichaud/Schreibtisch/Arbeit/code_expert/node_modules/jsdom/lib/jsdom/living/generated/Performance.js:100:15)
     at EventLoopMonitor._now (/home/sichaud/.meteor/packages/montiapm_agent/.2.46.1.tvqeu0.ijecd++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/evloop-monitor/lib/index.js:80:10)
     at Timeout._onTimeout (/home/sichaud/.meteor/packages/montiapm_agent/.2.46.1.tvqeu0.ijecd++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/evloop-monitor/lib/index.js:60:20)
     at listOnTimeout (internal/timers.js:557:17)
     at processTimers (internal/timers.js:500:7) {

```

**Comment by zodern** [comment]
We probably could disable some of the instrumentation when running app tests. What do you think @leonardoventurini?

**Comment by leonardoventurini** [comment]
@zodern why would the agent be even needed when running tests? Perhaps we could add an option to disable it completely?

I will look into this tomorrow

**Comment by zodern** [comment]
Normally it would not be needed, but I wouldn't be surprised if a team someplace does use monti apm during tests for some reason (maybe to recored the errors, or to use the event bus for some reason). It also allows tests to verify everything works correctly after updating the agent (we have released updates in the past that broke parts of some apps).

We could add an option to disable instrumenting, though it would be nice if we could fix this by default. Also the event loop monitor is currently setup by the System model, instead of being part of the instrumentation though it wouldn't be difficult to change it.

If we wanted to fix this specific error:
The error is from jsdom calling Performance.now, so it looks like eventloop-monitor is using [window.performance.now](https://github.com/kadirahq/node-eventloop-monitor/blob/d613470f62b3d311e0667737b33ae467ebe496da/lib/index.js#L72-L76) instead of the global [`performance.now`](https://github.com/myrne/performance-now/blob/614099d729aef5d7bdbb85c0d1060166d63d05c7/src/performance-now.coffee#L2). Since we only use the eventloop monitor on the server, we could fork the package and remove that code. It could also create a reference to `performance.now` immediately to ensure it is using the native function instead of a function set during tests.

I'm not sure how many other parts of the agent could cause similar issues, but this also is the first time I've seen the agent causing an error during tests.

**Comment by leonardoventurini** [comment]
I believe this is just a one off case, I don't think there will be other instances, this is a very specific flaw which the author did not take into account (using JSDOM in NodeJS).

I brought in and refactored the code for the event monitor, not many people use it and we have a specific need. It will be easier to maintain like this I believe. If needed I can create a separate package later.

In my refactor I did so it would actively detect NodeJS and attempt to use `perf_hooks` and otherwise `Date.now`, which also eliminates some dependencies which the original package had.

I will implement a flag to disable instrumentation as well.

**Comment by DavidSichau** [comment]
@leonardoventurini That sounds great. And a flag to disable the instrumentation would solve our issue.

**Comment by zodern** [comment]
@DavidSichau I published a beta version today which should fix the error. You can try it by running

```
meteor add montiapm:agent@2.47.0-beta.1 
```

We decided to fix the agent so it will work correctly during tests without you having to configure anything.

**Comment by zodern** [comment]
Version 2.47.0 has been released.
